spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codesnacks
    username: codesnacks
    password: geheim
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect